spring.application.name=msproduct
server.port=8080
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.profiles.active=@spring.profiles.active@
springdoc.swagger-ui.path=/docs
management.endpoints.web.exposure.include=prometheus,health,info
management.tracing.enabled=true
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces
logging.level.io.micrometer.tracing=DEBUG
logging.level.io.opentelemetry.exporter.otlp=DEBUG
logging.level.org.springframework.amqp.rabbit=DEBUG